name: Generate and Update Graphdoc
on:
  push:
    branches:
      - 'update-graphdoc/*'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: ${{ github.head_ref }}
          target_branch: master
          github_token: ${{ github.token }}
