name: Merge Master
on:
  push:
    branches:
      - 'update_graphdoc'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: update_graphdoc
          target_branch: master
          github_token: ${{ secrets.GH_PAT }}
