name: Generate and Update Graphdoc
on:
  create:
    branches:
      - 'update-graphdoc/*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: generate-graphdoc
      - run: |
          git config user.email "dev@vydia.com"
          git config user.name "Vydia"
          git add .
          git commit -m "update graphdoc"
          git push origin HEAD
  merge:
    needs: [update]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - run: |
          git pull origin HEAD
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: ${{ github.head_ref }}
          target_branch: master
          github_token: ${{ secrets.GH_PAT }}
