name: Update Graphdoc
on:
  create:
    branches:
      - 'update-graphdoc/*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - run: |
          yarn install
          git config user.email "dev@vydia.com"
          git config user.name "Vydia"
          git fetch origin update_graphdoc
          git checkout update_graphdoc
          yarn generate-graphdoc
          git add .
          git commit -m "update graphdoc"
          git push origin update_graphdoc --force
