name: Generate and Update Graphdoc
on:
  create:
    branches:
      - 'update-graphdoc/*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: generate-graphdoc
      - run: |
          git config user.email "dev@vydia.com"
          git config user.name "Vydia"
          git add .
          git commit -m "update graphdoc"
          git push origin ${GITHUB_REF#refs/heads/}
  merge:
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: ridedott/merge-me-action@v2
        with:
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, this repository uses `DOTTBOTT_TOKEN`.
          #
          # When using a custom token, it is recommended to leave the following
          # comment for other developers to be aware of the reasoning behind it:
          #
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
