name: Generate and Update Graphdoc
on:
  push:
    branches:
      - ^(update-graphdoc\/.*)$
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: generate-graphdoc
      - run: |
          git add .
          git commit -m "update graphdoc"
          git push
      - uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: ${{secrets.GITHUB_REF}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
