name: Generate and Update Graphdoc
on:
  create:
    branches:
      - '^(update-graphdoc\/.*)$'
  push:
    branches:
    - 'fix-update-graphdoc-'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{secrets.GITHUB_REF}}
          echo ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v2
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: generate-graphdoc
      # - run: |
      #     git config user.email "dev@vydia.com"
      #     git config user.name "Vydia"
      #     git add .
      #     git commit -m "update graphdoc"
      #     git push origin ${{secrets.GITHUB_REF}}
      # - uses: devmasx/merge-branch@v1.4.0
      #   with:
      #     label_name: auto-merge ${{secrets.GITHUB_REF}}
      #     target_branch: master
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
