name: Update Graphdoc
on:
  create:
    branches:
      - 'update-graphdoc/*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - run: |
          git config user.email "dev@vydia.com"
          git config user.name "Vydia"
          git fetch
          git checkout update_graphdoc
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: generate-graphdoc
      - run: |
          git add .
          git commit -m "update graphdoc"
          git push origin update_graphdoc --force
